import type { BlogCollections } from "~/types/config";
import type { ImageInfo, MainLinkConfig, MusicInfo } from "~/types/common";
import type { DetailWorkBlogCardParams } from "~/types/components";

export const BLOG_COLLECTIONS: BlogCollections[] = [
	"front_end",
	"back_end",
	"gms2",
	"algorithm",
	"deep_learning",
];

export const DETAIL_NAME = "一颗没梦想的苹果";

export const DETAIL_JOB = "还是学生";

export const DETAIL_HOBBY = "大概是 coding...";

export const DETAIL_STATE = "摸鱼中...";

export const DETAIL_SKILLS = [
	"html",
	"css",
	"javascript",
	"ts",
	"vue",
	"java",
	"c++",
	"gml",
	"jsx",
];

export const DETAIL_TARGET = "致力于动画，交互与视觉体验";

export const DETAIL_EMPTY = "一般你看不到的";

export const DETAIL_WORK_BLOG_DATA: DetailWorkBlogCardParams[] = [
	{
		title: "image",
		subtitle: "图集",
		icon: "&#xe997;",
		content: "保留美丽的部分",
		previewImage: "/images/components/imagePreview.png",
		backgroundImage: "/images/components/imagePreview.png",
	},
	{
		title: "item",
		subtitle: "沙盒",
		icon: "&#xe994;",
		content: "尝试实现新鲜想法",
		previewImage: "/images/components/itemPreview.png",
		backgroundImage: "/images/components/itemBackground.png",
	},
	{
		title: "music",
		subtitle: "音乐",
		icon: "&#xe99a;",
		content: "静静欣赏音乐",
		previewImage: "/images/components/musicPreview.png",
		backgroundImage: "/images/components/musicPreview.png",
	},
	{
		title: "blog",
		subtitle: "笔记",
		icon: "&#xe99c;",
		content: "记录一些必要信息",
		previewImage: "/images/components/blogPreview.png",
		backgroundImage: "/images/components/blogBackground.png",
	},
	{
		title: "main",
		subtitle: "主页",
		icon: "&#xe7e8;",
		content: "从这里开始探索",
		previewImage: "/images/components/mainPreview.png",
		backgroundImage: "/images/components/mainPreview.png",
	},
];
export const LOADING_TIPS: string[] = ["这里没有提示", "主页里有些隐蔽的链接"];

export const IMAGE_DATAS: ImageInfo[] = [
	{
		name: "铃仙（undertale 特供版）",
		author: "一颗没梦想的苹果",
		path: "/images/collections/c629be96-7085-4bcf-950f-dffc6dd36aaf.png",
		option: {
			pixel: true,
			themeColor: "#ffffff",
			border: true,
		},
	},
	{
		name: "",
		author: "",
		path: "/images/collections/140786992_p0.jpg",
	},
	{
		name: "UJ!LB“Bullet Train - Death Station”",
		author: "BiBimusim2",
		path: "/images/collections/IMG_1324.png",
		option: {
			themeColor: "#ffffff",
			border: true,
		},
	},
	{
		name: "UJ!“Insanity Duo”",
		author: "BiBimusim2",
		path: "/images/collections/IMG_1326.webp",
		option: {
			themeColor: "#800080",
			border: true,
		},
	},
	{
		name: "[K.V.M - Unjustice] Phase 2",
		author: "BiBimusim2",
		path: "/images/collections/IMG_1323.webp",
		option: {
			themeColor: "#ffffff",
			border: true,
		},
	},
	{
		name: "MB!TouhouTale",
		author: "タングステン",
		path: "/images/collections/illust_130516251_20250522_000220.jpg",
		option: {
			themeColor: "#ffff00",
			border: true,
		},
	},
];

export const IMAGE_EMPTY = "未知";

export const LONG_PRESS_TIME = 500;

export const MAIN_NAME = "FRISK";

export const MAIN_LV = 19;

export const MAIN_HP = 92;

export const MAIN_LINKS: MainLinkConfig[] = [
	{
		pos: { x: 720, y: 760 },
		size: { width: 50, height: 90 },
		themeColor: "#ffd500",
		content: "前端基础入门",
		target: "/blogs/html",
	},
	{
		pos: { x: 1810, y: 860 },
		size: { width: 40, height: 90 },
		themeColor: "#00a300",
		content: "后端进阶框架",
		target: "/blogs/springboot",
	},
	{
		pos: { x: 150, y: 280 },
		size: { width: 50, height: 90 },
		themeColor: "#000dff",
		content: "算法练习题",
		target: "/blogs/algorithm_consolidation",
	},
	{
		pos: { x: 1700, y: 400 },
		size: { width: 40, height: 80 },
		themeColor: "#d829ff",
		content: "GML 函数参考",
		target: "/blogs/common_functions",
	},
];

export const MAIN_EMPTY = "暂无信息";

export const MUSIC_DATAS: MusicInfo[] = [
	{
		name: "散落的烛光　～ Candlelight",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/01 散落的烛光　～ Candlelight.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "黑暗少女　～ Dark girl",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/02 黑暗少女　～ Dark girl.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "湖面的冰之曲　～ The rhythm of ice",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/03 湖面的冰之曲　～ The rhythm of ice.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "妖精背水一战　～ A dare",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/04 妖精背水一战　～ A dare.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "东方梦之馆　～ East castle",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/05 东方梦之馆　～ East castle.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "风卷残云　～ Kongfu storm",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/06 风卷残云　～ Kongfu storm.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "沉睡中的大图书馆　～ The library in silence",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/07 沉睡中的大图书馆　～ The library in silence.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "华丽的恶魔之舞　～ The little devil dance",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/08 华丽的恶魔之舞　～ The little devil dance.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "时钟走廊　～ Flowing time",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/09 时钟走廊　～ Flowing time.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "钟楼战场　～ Bell tower",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/10 钟楼战场　～ Bell tower.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "绯月之主　～ The master of red moon",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/11 绯月之主　～ The master of red moon.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "无尽的命运　～ Endless fate",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/12 无尽的命运　～ Endless fate.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "幕华祭　～红月篇～",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/13 幕华祭　～红月篇～.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "百年少女怪谈　～ The mystery",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/14 百年少女怪谈　～ The mystery.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "淋满鲜血的还有谁呢　～ Who cares",
		cover: "/images/cover/東方幕華祭 红月篇.png",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 红月篇 OST/15 淋满鲜血的还有谁呢　～ Who cares.mp3",
		folder: "東方幕華祭 红月篇 OST",
	},
	{
		name: "常世之乡",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/01.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "无穷无尽的白色",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/02.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "梦境演剧",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/03.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "迷途之家的野猫",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/04.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "橙",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/05.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "喜欢西洋乐的人偶们",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/06.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "看不破的人偶剧",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/07.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "春岚",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/08.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "云霄之上花与舞",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/09.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "通向往生之界的阶梯",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/10.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "极乐庄严",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/11.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "狂樱之舞",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/12.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "生死之间花吹雪",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/13.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "飞舞吧！永世的繁花",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/14.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "幕华祭～春雪篇～",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/15.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "感知崩坏的空间",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/16.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "人类与妖怪的铁幕",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/17.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "月下花见急行",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/18.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "地狱行乐",
		cover: "/images/cover/東方幕華祭 春雪篇.jpg",
		artist: "StarX",
		path: "/sounds/musics/東方幕華祭 春雪篇 OST/19.mp3",
		folder: "東方幕華祭 春雪篇 OST",
	},
	{
		name: "超古代の生き血",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/1 超古代の生き血.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "天星の河渉り",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/2 天星の河渉り.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "螺旋の縁　～ Red Marriage.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/3 螺旋の縁　～ Red Marriage.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "幻想ライトタウン",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/4 幻想ライトタウン.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "霊蝶は宙を舞う",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/5 霊蝶は宙を舞う.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "ディープ・アクアマリン",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/6 ディープ・アクアマリン.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "爆裂氷界石　～ Oxygen Conversion.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/7 爆裂氷界石　～ Oxygen Conversion.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "エスメラルダ石窟",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/8 エスメラルダ石窟.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "阿僧祇の信世界　～ World Trust.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/9 阿僧祇の信世界　～ World Trust.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "玉石の協奏曲",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/10 玉石の協奏曲.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "夢の孤高揚羽鉄扇　～ Sound of a nightmare.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/11 夢の孤高揚羽鉄扇　～ Sound of a nightmare.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "アカデミア・トークン",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/12 アカデミア・トークン.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "計都羅業の祝殷 ～ Taisui Xingjun.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/13 計都羅業の祝殷 ～ Taisui Xingjun.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "生命体監察史記",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/14 生命体監察史記.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "逢天宇宙儀　～ Space Surveillance.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/15 逢天宇宙儀　～ Space Surveillance.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "スターインデペンデントデイズ",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/16 スターインデペンデントデイズ.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "七色灯の燈る路",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/17 七色灯の燈る路.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "水晶華灯怪導　～ crystal Lantern.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/18 水晶華灯怪導　～ crystal Lantern.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "ブラックオパール・ラビリンス",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/19 ブラックオパール・ラビリンス.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "二億四千万年の輪廻　～ Sandplay Toys Clay.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/20 二億四千万年の輪廻　～ Sandplay Toys Clay.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "絶望と言う名の遊戯輪廻",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/21 絶望と言う名の遊戯輪廻.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "揚羽蝶と孔雀石のロンド　～ versicolor.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/22 揚羽蝶と孔雀石のロンド　～ versicolor.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "煉獄のラクシャーシ　～ Combat Heaven Rasetsu.",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/23 煉獄のラクシャーシ　～ Combat Heaven Rasetsu.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "少女達の弾幕浪曼",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/24 少女達の弾幕浪曼.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "いにしえの言の葉",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/25 いにしえの言の葉.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "黄河延命　～ Ancient Dreams...",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/26 黄河延命　～ Ancient Dreams.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "プレイヤーズスコア",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/27 プレイヤーズスコア.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "宵宮の宝石箱",
		cover: "/images/cover/東方宝天京～Treasure_Castle_Labyrinth.jpg",
		artist: "Pesot.jp",
		path: "/sounds/musics/東方宝天京 ～ Treasure Castle Labyrinth OST/28 宵宮の宝石箱.mp3",
		folder: "東方宝天京 ～ Treasure Castle Labyrinth OST",
	},
	{
		name: "極彩色の夢現",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "緋子望",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/極彩色の夢現.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "紅き黎明に歌垣を",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "緋子望",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/紅き黎明に歌垣を.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "古の六歌仙 ～ Love Letter From？",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "緋子望",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/古の六歌仙 ～ Love Letter From？.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "吹き荒ぶ風を突き抜けて",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "Monday",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/吹き荒ぶ風を突き抜けて.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "不吹堂の飛威綱",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "壱太",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/不吹堂の飛威綱.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "暗闇に舞え、石の花吹雪",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "Monday",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/暗闇に舞え、石の花吹雪.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "影絶つ速さのサラブレッド",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "夜狐夜叉",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/影絶つ速さのサラブレッド.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "伽藍の霊殿 ～ Hollow Mansion",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "NED",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/伽藍の霊殿 ～ Hollow Mansion.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "スターヴカラミティー",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "NED",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/スターヴカラミティー.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "タタラ・ザ・ファーネース",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "NED",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/タタラ・ザ・ファーネース.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "桔梗塚伝説 ～ Black Ventus",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "Wanwan",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/桔梗塚伝説 ～ Black Ventus.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "鋼は炎より生じて大地に帰る",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "夜狐夜叉",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/鋼は炎より生じて大地に帰る.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "軍神五兵の反乱者 ～ REBELLION God Force",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "Wanwan",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/軍神五兵の反乱者 ～ REBELLION God Force.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "根の国のレイライン",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "maceknight",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/根の国のレイライン.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "子午線を割る逆鱗 ～ Dragon's Dream",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "壱太",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/子午線を割る逆鱗 ～ Dragon's Dream.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "鬼も内よで福来たる",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "緋子望",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/鬼も内よで福来たる.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "奈落のオクトーバーフェスト",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "古山キリヲ",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/奈落のオクトーバーフェスト.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
	{
		name: "プレイヤーズスコア",
		cover: "/images/cover/東方鬼葬剣 ～ Infinite Blade Pavilion.jpg",
		artist: "古山キリヲ",
		path: "/sounds/musics/東方鬼葬剣 ～ Infinite Blade Pavilion. OST/プレイヤーズスコア.mp3",
		folder: "東方鬼葬剣 ～ Infinite Blade Pavilion. OST",
	},
];
