name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - nuxt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: corepack enable

      - run: yarn install --frozen-lockfile

      - run: yarn nuxi generate

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
